name: htmldrop-cms
region: nyc

services:
  - name: web
    environment_slug: node-js
    github:
      repo: htmldrop/htmldrop
      branch: main
      deploy_on_push: true
    build_command: npm install
    run_command: npm run migrate && npm run seed && npm start
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /
    health_check:
      http_path: /api/health
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: DB_CLIENT
        value: pg
      - key: DB_HOST
        value: ${db.HOSTNAME}
      - key: DB_PORT
        value: ${db.PORT}
      - key: DB_USER
        value: ${db.USERNAME}
      - key: DB_PASSWORD
        value: ${db.PASSWORD}
      - key: DB_NAME
        value: ${db.DATABASE}
      - key: TABLE_PREFIX
        value: hd_
      - key: JWT_SECRET
        type: SECRET
        value: CHANGE_THIS_TO_RANDOM_SECRET
      - key: JWT_REFRESH_SECRET
        type: SECRET
        value: CHANGE_THIS_TO_RANDOM_SECRET
      - key: SESSION_SECRET
        type: SECRET
        value: CHANGE_THIS_TO_RANDOM_SECRET
      - key: JWT_EXPIRES_IN
        value: 1h
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d

databases:
  - name: db
    engine: PG
    version: "15"
    production: false
    cluster_name: htmldrop-db
